version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - 27017:27017
    networks:
      - mongo-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./mongo-data:/data/db
    # restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    ports:
      - 8081:8081
    networks:
      - mongo-network
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongodb:27017/
    restart: unless-stopped

networks:
  mongo-network:
    # name: mongo-network
    driver: bridge

# volumes:
#   mongo-data: